version: '3.3'

services:
  registry:
    image: "registry"
    ports:
    - "5000:5000"
    volumes:
    - "registry:/var/lib/registry"

  apache:
    image: "httpd"
    ports:
    - "80:80"

  jenkins:
    image: jenkins
    ports:
    - "8080:8080"

volumes:
    registry:
